version: '2'
services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 8087:80 
    volumes:
      - ${APPDATA_PATH}/wiki-wordpress/uploads:/usr/local/etc/php/conf.d/uploads.ini
      - ${APPDATA_PATH}/wiki-wordpress/wp-app:/var/www/html 
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    depends_on:
      - db
    networks:
      - client1
    restart: unless-stopped
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3308:3306 
    volumes:
      - ${APPDATA_PATH}/wiki-wordpress/mysql:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - client1
networks:
  client1:
      driver: bridge
