services:
  yt-dlp-webui-xbuild:
    image: ruseler/yt-dlp-webui-xbuild:latest
    environment:
      - TZ=${TZ}
    ports:
      - ${HOST_PORT}:3033
    volumes:
      - ${DOWNLOAD_PATH}:/downloads
    healthcheck:
      test: curl -f http://localhost:${HOST_PORT} || exit 1
    restart: unless-stopped
